### ISSUE TITLE
Proposed filter

### ISSUE THREAD

**Issue by kprovance** [davidsherlock/edd-purchase-download-button#1]
First, thank you for the helpful plugin.  We use it on the Redux Framework site.  I am currently redesigning out site, and in making an EDD compatible theme (fun stuff there), I've discovered that when accessing a download page, where the user has purchased the item, and it's a bundled product, I get several rows of buttons that say "Download".  It's difficult for the client to know which download is which.  I played with the filter hook for edd_purchases_download_button to see if I could force in the item names on the button, to no avail.  it needs to happen within the foreach on the download_ids.  So, I'd like to propose a filter in that section of code given the developer a chance to override the output on the button for 'Download' to the actual item name.  I've already written the code on my local.  I'd be happy to submit a pull request for your review.  The code will not break any existing functionally or cause backward compatibility issues.

Thanks!

**Comment by kprovance** [comment]
Pull request submitted.

**Comment by davidsherlock** [comment]
Thanks for the fixes @kprovance, I have merged your commits!

**Comment by kprovance** [comment]
Awesome!  Grazie mille
